name: CD Process
on:
  push:
    branches: [master]
jobs:
  Pytest:
    runs-on: ubuntu-latest
    container: python:3.10.6-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install Python Dependencies
        run: pip install --upgrade pip && pip install Flask pytest
      - name: Run Python Unit Tests
        run: python3 -m pytest tests/

  Build-Deploy: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: docker build -t jonathanarturocando/devsu-devops:${{ github.sha }} .
      - name: Push docker image
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username jonathanarturocando --password-stdin
          docker push jonathanarturocando/devsu-devops:${{ github.sha }}
      - name: Copy files to remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ec2-user/devsu-devops"
      - name: Deploying Docker container ...
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/devsu-devops && docker compose up -d
